# Cloudflare Pages Build Configuration
# Deploy Worker from integrations/cloudflare directory

[build]
  command = "npx wrangler deploy"
  base = "integrations/cloudflare"

[build.environment]
  NODE_VERSION = "20.18.0"

