# Cloudflare Pages Build Configuration
# This file tells Cloudflare Pages to deploy the Worker from the correct directory

# Build settings
[build]
  # Change to the Worker directory and deploy
  command = "npx wrangler deploy"
  # Root directory containing wrangler.toml
  base = "integrations/cloudflare"

# Environment variables
[build.environment]
  NODE_VERSION = "20.18.0"
