name = "fittrack-trainer"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "4f61fb25b226afc8c61c1b069ea14ed9"
workers_dev = true

compatibility_flags = [
  "nodejs_compat"
]

# Cloudflare bindings - matching the parent worker's bindings
[[d1_databases]]
binding = "FITTRACK_D1"
database_name = "fittrack-pro-db"
database_id = "32046a7f-9f95-4b84-a79d-b7895d0e6eae"

[[r2_buckets]]
binding = "R2_UPLOADS"
bucket_name = "fittrack-uploads"

[[kv_namespaces]]
binding = "FITTRACK_KV"
id = "1f558809e4d54eab84e09931e73584f9"

[ai]
binding = "AI"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "fittrack_trainer_events"

# Environment variables
[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "*"
RL_AUTH_PER_MINUTE = "8"
RL_USDA_PER_MINUTE = "5"
MAX_UPLOAD_MB = "5"
EXERCISEDB_API_KEY = "01a44cbd89msh864c4e87aba2d22p10f83cjsn2bea18eb05ec"
EXERCISEDB_HOST1 = "exercisedb.p.rapidapi.com"
EXERCISEDB_HOST2 = "exercise-db-fitness-workout-gym.p.rapidapi.com"
THEMEALDB_API_URL = "https://www.themealdb.com/api/json/v1/1"
USDA_API_KEY = "uH2TDQWthtdFvLn6Bz4wXe2VLBBGwA3SbeHPnGkJ"
USDA_API_URL = "https://api.nal.usda.gov/fdc/v1"

[observability]
enabled = true


