name = "fittrack-trainer"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "4f61fb25b226afc8c61c1b069ea14ed9"
workers_dev = true

compatibility_flags = [
  "nodejs_compat"
]

# Cloudflare bindings - matching the parent worker's bindings
[[d1_databases]]
binding = "FITTRACK_D1"
database_name = "fittrack-pro-db"
database_id = "32046a7f-9f95-4b84-a79d-b7895d0e6eae"

[[r2_buckets]]
binding = "R2_UPLOADS"
bucket_name = "fittrack-uploads"

[[kv_namespaces]]
binding = "FITTRACK_KV"
id = "1f558809e4d54eab84e09931e73584f9"

[ai]
binding = "AI"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "fittrack_trainer_events"

# Environment variables
[vars]
ENVIRONMENT = "production"
ALLOWED_ORIGINS = "*"
RL_AUTH_PER_MINUTE = "8"
RL_USDA_PER_MINUTE = "5"
MAX_UPLOAD_MB = "5"

[observability]
enabled = true


