name: Branch Protection Setup

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - status

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    name: Configure Branch Protection
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply branch protection rules
        if: github.event.inputs.action == 'apply'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Branch protection rules for main branch
            const protection = {
              required_status_checks: {
                strict: true,
                contexts: ['Deploy Worker']
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false,
                required_approving_review_count: 0,
                require_last_push_approval: false
              },
              restrictions: null,
              required_linear_history: false,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true,
              lock_branch: false,
              allow_fork_syncing: true
            };
            
            try {
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch: 'main',
                ...protection
              });
              
              core.notice('✅ Branch protection rules applied to main branch');
            } catch (error) {
              core.setFailed(`Failed to apply branch protection: ${error.message}`);
            }

      - name: Check branch protection status
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            try {
              const { data } = await github.rest.repos.getBranchProtection({
                owner,
                repo,
                branch: 'main'
              });
              
              core.notice('📋 Current branch protection rules:');
              core.notice(JSON.stringify(data, null, 2));
            } catch (error) {
              core.warning(`Could not fetch branch protection: ${error.message}`);
              core.notice('ℹ️ Branch protection may not be configured yet. Run with action=apply to set it up.');
            }
