name: Deploy Cloudflare Worker

on:
  push:
    paths:
      - 'integrations/cloudflare/fittrack-trainer/**'
      - '.github/workflows/deploy-cloudflare-worker.yml'
      - 'package.json'
      - 'wrangler.toml'
      - 'wrangler.jsonc'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish Cloudflare Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          cd integrations/cloudflare/fittrack-trainer
          wrangler deploy --name fittrack-trainer --config wrangler.toml
