name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
    paths:
      - 'integrations/cloudflare/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: integrations/cloudflare/package.json

      - name: Install dependencies
        working-directory: integrations/cloudflare
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
          fi

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: integrations/cloudflare
          command: deploy

      - name: Verify deployment
        run: |
          echo "✅ Worker deployed successfully!"
          echo "🔗 Worker URL: https://fittrack-pro-desktop.rehchu1.workers.dev"
