name = "fittrack-dependency-workflow"
main = "workflows/dependency-workflow.js"
compatibility_date = "2025-10-28"
compatibility_flags = ["nodejs_compat"]

# Account ID
account_id = "4f61fb25b226afc8c61c1b069ea14ed9"

# Workflow binding
[[workflows]]
binding = "DEPENDENCY_WORKFLOW"
name = "fittrack-dependency-workflow"
class_name = "DependencyUpdateWorkflow"

# Cron trigger - runs every Monday at 9 AM UTC
[triggers]
crons = ["0 9 * * 1"]

# Environment variables
[vars]
GITHUB_REPO = "Rehchu/FitTrack-Pro"
